CREATE TABLE [FLASHCARDS].[dbo].[tb_FlashCards] (
    CardID INT PRIMARY KEY IDENTITY(1,1),
    Front TEXT NOT NULL,
    Back TEXT NOT NULL,
    StackID INT NOT NULL,
    FOREIGN KEY (StackID) REFERENCES tb_Stacks(StackID) ON DELETE CASCADE
);



